TDTP_IDENTIFIERS = {
    1: "Gas",
    2: "Brake",
    3: "SWA",
    4: "Lowbeam",
    5: "Highbeam",
    6: "Horn",
    7: "Indicator_L",
    8: "Indicator_R",
    9: "IMU_AX",
    10: "IMU_AY",
    11: "IMU_AZ",
    12: "IMU_YAW",
    13: "IMU_PITCH",
    14: "IMU_ROLL",
    15: "BATT_U",
    16: "PACKAGE_LOSS",
    17: "Lidar",
}
